
# Переменные
PYTHON=python
SRC_DIR=src
INTERFACE_FILE=$(SRC_DIR)/serial_interface.py
LOGIC_FILE=$(SRC_DIR)/serial_logic.py
MAIN_FILE=main.py

# Цели
.PHONY: run clean

run: 
	$(PYTHON) $(MAIN_FILE)

clean: 
	del /S *.pyc
